package ma.ilias.dbmanagementbe.enums;

public enum ActionType {
    LOGIN, LOGOUT,
    CREATE_SCHEMA, UPDATE_SCHEMA, DELETE_SCHEMA,
    CREATE_TABLE, UPDATE_TABLE, DELETE_TABLE,
    CREATE_RECORD, UPDATE_RECORD, DELETE_RECORD,
    CREATE_INDEX, DELETE_INDEX,
    CREATE_USER, UPDATE_USER, DELETE_USER,
    ACTIVATE_USER, DEACTIVATE_USER,
    CREATE_ROLE, UPDATE_ROLE, DELETE_ROLE,
    EXPORT_DATA, IMPORT_DATA
}
