package ma.ilias.dbmanagementbe.enums;

public enum ActionType {
    LOGIN, LOGOUT,
    CREATE_SCHEMA, DELETE_SCHEMA,
    CREATE_TABLE, UPDATE_TABLE, DELETE_TABLE,
    CREATE_COLUMN, UPDATE_COLUMN, DELETE_COLUMN,
    CREATE_INDEX, DELETE_INDEX,
    CREATE_VIEW, UPDATE_VIEW, DELETE_VIEW,
    CREATE_RECORD, UPDATE_RECORD, DELETE_RECORD,
    CREATE_MULTIPLE_RECORDS, UPDATE_MULTIPLE_RECORDS, DELETE_MULTIPLE_RECORDS,
    CREATE_USER, UPDATE_USER, DELETE_USER,
    ACTIVATE_USER, DEACTIVATE_USER,
    CREATE_ROLE, UPDATE_ROLE, DELETE_ROLE,
    CREATE_PERMISSION, UPDATE_PERMISSION, DELETE_PERMISSION,
    EXECUTE_SQL,
    EXPORT_DATA,
}
